name: Build & Push Keycloak (DOCR)

on:
  push:
    branches: [ main, prereleased, released ]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: main
            env: dev
            tag: latest-dev
          - branch: prereleased
            env: stage
            tag: latest-stage
          - branch: released
            env: prod
            tag: latest
    if: github.ref_name == matrix.branch

    environment: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v4

      - name: Set tags
        id: vars
        run: |
          SHA_TAG=${GITHUB_SHA::7}
          echo "TAG_SHA=${SHA_TAG}" >> $GITHUB_OUTPUT
          echo "TAG_LATEST=${{ matrix.env }}" >> $GITHUB_OUTPUT

      - name: Login to DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Docker registry login
        run: doctl registry login --expiry-seconds 600

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Build image that compiles theme from repo
      - name: Build & Push (build-from-repo)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.keycloak
          push: true
          tags: |
            registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}/${{ secrets.DOCR_REPO }}:${{ steps.vars.outputs.TAG_SHA }}
            registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}/${{ secrets.DOCR_REPO }}:${{ steps.vars.outputs.TAG_LATEST }}
          cache-from: type=registry,ref=registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}/${{ secrets.DOCR_REPO }}:buildcache
          cache-to: type=registry,ref=registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}/${{ secrets.DOCR_REPO }}:buildcache,mode=max