name: Storybook → GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: storybook-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
      # Adjust version & package manager (yarn/pnpm/npm) to your repo
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build Storybook
        run: |
          # Script should output to storybook-static/
          yarn prestart
          yarn build-storybook

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
